In [1]:
import numpy as np
import pandas as pd

import yfinance as yf
from fredapi import Fred

import os
from dotenv import load_dotenv
load_dotenv()


import matplotlib.pyplot as plt
import seaborn as sns

# MacroEconomic Data

In [2]:
fred_api_key = os.getenv('FRED_API_KEY')

start = '1990-01-01'
end = '2025-12-31'

In [3]:
macro_variables = [
    # Real activity
    'INDPRO', 'W875RX1',
    # Labour market
    'UNRATE', 'ICSA', 'CCSA',
    # Inflation
    'CPIAUCSL',
    # Energy / commodities
    'DCOILWTICO',
    # Financial conditions
    'VIXCLS', 'BAA10Y', 'DBAA', 'DAAA', 'T10Y2Y',
    # Monetary policy
    'FEDFUNDS',
    # Sentiment & housing
    'UMCSENT', 'HOUST',
    # Money supply
    'M2SL',
    # Dollar index — three-way splice for full 1990 coverage:
    # TWEXMMTH (1973-present, major currencies, monthly)
    # TWEXB    (1995-2019, broad, weekly/monthly, discontinued)
    # DTWEXBGS (2006-present, broad goods+services, current)
    # Splice: TWEXMMTH for 1990-1994, TWEXB for 1995-2005,
    #         DTWEXBGS from 2006 onward.  Scale at each join.
    'TWEXMMTH', 'TWEXB', 'DTWEXBGS',
]

In [4]:
fred = Fred(api_key=fred_api_key)

In [5]:
series_dict = {}

for var in macro_variables:
    series_dict[var] = fred.get_series(var, observation_start=start,
                                        observation_end=end)

df_raw = pd.DataFrame(series_dict)
print(f'Raw data shape: {df_raw.shape}')
df_raw.head(10)

Raw data shape: (11332, 19)

,INDPRO,W875RX1,UNRATE,ICSA,CCSA,CPIAUCSL,DCOILWTICO,VIXCLS,BAA10Y,DBAA,DAAA,T10Y2Y,FEDFUNDS,UMCSENT,HOUST,M2SL,TWEXMMTH,TWEXB,DTWEXBGS
1990-01-01,61.729,7184.9,5.4,NaN,NaN,127.5,NaN,NaN,NaN,NaN,NaN,NaN,8.23,93.0,1551.0,3166.8,92.4069,NaN,NaN
1990-01-02,NaN,NaN,NaN,NaN,NaN,NaN,22.88,17.24,1.91,9.85,8.87,0.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-03,NaN,NaN,NaN,NaN,NaN,NaN,23.81,18.19,1.87,9.86,8.90,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-04,NaN,NaN,NaN,NaN,NaN,NaN,23.41,19.22,1.86,9.84,8.89,0.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-05,NaN,NaN,NaN,NaN,NaN,NaN,23.07,20.11,1.89,9.88,8.88,0.09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-06,NaN,NaN,NaN,355000.0,2347000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-08,NaN,NaN,NaN,NaN,NaN,NaN,21.64,20.26,1.86,9.88,8.90,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-09,NaN,NaN,NaN,NaN,NaN,NaN,22.25,22.20,1.84,9.86,8.92,0.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-10,NaN,NaN,NaN,NaN,NaN,NaN,22.90,22.44,1.85,9.88,8.91,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-11,NaN,NaN,NaN,NaN,NaN,NaN,23.15,20.05,1.82,9.86,8.92,0.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_raw.head(10)

,INDPRO,W875RX1,UNRATE,ICSA,CCSA,CPIAUCSL,DCOILWTICO,VIXCLS,BAA10Y,DBAA,DAAA,T10Y2Y,FEDFUNDS,UMCSENT,HOUST,M2SL,TWEXMMTH,TWEXB,DTWEXBGS
1990-01-01,61.729,7184.9,5.4,NaN,NaN,127.5,NaN,NaN,NaN,NaN,NaN,NaN,8.23,93.0,1551.0,3166.8,92.4069,NaN,NaN
1990-01-02,NaN,NaN,NaN,NaN,NaN,NaN,22.88,17.24,1.91,9.85,8.87,0.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-03,NaN,NaN,NaN,NaN,NaN,NaN,23.81,18.19,1.87,9.86,8.90,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-04,NaN,NaN,NaN,NaN,NaN,NaN,23.41,19.22,1.86,9.84,8.89,0.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-05,NaN,NaN,NaN,NaN,NaN,NaN,23.07,20.11,1.89,9.88,8.88,0.09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-06,NaN,NaN,NaN,355000.0,2347000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-08,NaN,NaN,NaN,NaN,NaN,NaN,21.64,20.26,1.86,9.88,8.90,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-09,NaN,NaN,NaN,NaN,NaN,NaN,22.25,22.20,1.84,9.86,8.92,0.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-10,NaN,NaN,NaN,NaN,NaN,NaN,22.90,22.44,1.85,9.88,8.91,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-11,NaN,NaN,NaN,NaN,NaN,NaN,23.15,20.05,1.82,9.86,8.92,0.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df_monthly = df_raw.resample('ME').last()

In [8]:
df_monthly.head(10)

,INDPRO,W875RX1,UNRATE,ICSA,CCSA,CPIAUCSL,DCOILWTICO,VIXCLS,BAA10Y,DBAA,DAAA,T10Y2Y,FEDFUNDS,UMCSENT,HOUST,M2SL,TWEXMMTH,TWEXB,DTWEXBGS
1990-01-31,61.7290,7184.9,5.4,345000.0,2316000.0,127.5,22.69,25.36,1.68,10.11,9.15,0.15,8.23,93.0,1551.0,3166.8,92.4069,NaN,NaN
1990-02-28,62.2896,7210.5,5.3,350000.0,2347000.0,128.0,21.55,21.99,1.68,10.19,9.25,0.08,8.24,89.5,1437.0,3179.2,92.4490,NaN,NaN
1990-03-31,62.5999,7216.8,5.2,346000.0,2365000.0,128.6,20.34,19.73,1.58,10.23,9.39,0.01,8.28,91.3,1289.0,3190.1,94.3127,NaN,NaN
1990-04-30,62.4359,7262.7,5.4,363000.0,2403000.0,128.9,18.50,19.52,1.50,10.54,9.63,0.08,8.26,93.9,1248.0,3201.6,94.3080,NaN,NaN
1990-05-31,62.6258,7252.9,5.4,359000.0,2431000.0,129.1,17.47,17.37,1.71,10.31,9.37,0.10,8.18,90.6,1212.0,3200.6,93.0176,NaN,NaN
1990-06-30,62.8382,7261.7,5.2,364000.0,2442000.0,129.9,17.05,15.50,1.79,10.22,9.24,0.19,8.29,88.3,1177.0,3213.7,93.0054,NaN,NaN
1990-07-31,62.7284,7289.9,5.5,369000.0,2461000.0,130.5,20.57,21.11,1.77,10.13,9.21,0.45,8.15,88.2,1171.0,3224.5,90.4680,NaN,NaN
1990-08-31,62.9475,7242.0,5.7,394000.0,2540000.0,131.6,27.45,29.90,1.69,10.55,9.58,0.79,8.13,76.4,1115.0,3242.0,88.1775,NaN,NaN
1990-09-30,62.9523,7231.3,5.9,404000.0,2644000.0,132.5,39.53,29.11,1.94,10.76,9.60,0.80,8.20,72.8,1110.0,3254.6,87.0211,NaN,NaN
1990-10-31,62.5845,7159.5,5.9,440000.0,2787000.0,133.4,35.31,30.04,2.13,10.78,9.49,0.88,8.11,63.9,1014.0,3259.3,84.4191,NaN,NaN

In [9]:
df_monthly.isna().sum()

INDPRO          0
W875RX1         0
UNRATE          1
ICSA            0
CCSA            0
CPIAUCSL        1
DCOILWTICO      0
VIXCLS          0
BAA10Y          0
DBAA            0
DAAA            0
T10Y2Y          0
FEDFUNDS        0
UMCSENT         0
HOUST           0
M2SL            0
TWEXMMTH       72
TWEXB         131
DTWEXBGS      192
dtype: int64

In [10]:
# Forward-fill series released less frequently than monthly
for col in ['UNRATE', 'CPIAUCSL', 'CCSA',
            'TWEXMMTH', 'TWEXB', 'DTWEXBGS',
            'DBAA', 'DAAA']:
    if col in df_monthly.columns:
        df_monthly[col] = df_monthly[col].ffill()

# ── Three-way splice for full dollar index from 1990 ─────────────────
# Coverage by segment:
#   TWEXMMTH : 1973 – present  (major currencies, monthly)
#   TWEXB    : 1995 – 2019     (broad basket, discontinued)
#   DTWEXBGS : 2006 – present  (broad basket goods+services, current)
#
# Strategy:
#   1. Use DTWEXBGS from 2006 onward (most current, broadest)
#   2. Extend back to 1995 with TWEXB, scaled to match DTWEXBGS
#      at the Jan 2006 splice point
#   3. Extend back to 1990 with TWEXMMTH, scaled to match TWEXB
#      at the Jan 1995 splice point
# Both TWEXB and TWEXMMTH are on the same Federal Reserve H.10
# release as DTWEXBGS — same methodology, different baskets.

cols = ['TWEXMMTH', 'TWEXB', 'DTWEXBGS']
if all(c in df_monthly.columns for c in cols):

    splice1 = pd.Timestamp('2006-01-31')  # TWEXB → DTWEXBGS
    splice2 = pd.Timestamp('1995-01-31')  # TWEXMMTH → TWEXB

    # Scale TWEXB to match DTWEXBGS at splice1
    ov1 = df_monthly.loc[
        (df_monthly.index >= splice1) &
        df_monthly['TWEXB'].notna() &
        df_monthly['DTWEXBGS'].notna()
    ]
    scale1 = (ov1['DTWEXBGS'] / ov1['TWEXB']).median() if len(ov1) else 1.0

    # Scale TWEXMMTH to match scaled-TWEXB at splice2
    ov2 = df_monthly.loc[
        (df_monthly.index >= splice2) &
        df_monthly['TWEXMMTH'].notna() &
        df_monthly['TWEXB'].notna()
    ]
    scale2 = ((ov2['TWEXB'] * scale1) / ov2['TWEXMMTH']).median() if len(ov2) else 1.0

    seg_pre95  = df_monthly.loc[
        df_monthly.index < splice2, 'TWEXMMTH'
    ] * scale2
    seg_95_05  = df_monthly.loc[
        (df_monthly.index >= splice2) & (df_monthly.index < splice1), 'TWEXB'
    ] * scale1
    seg_post06 = df_monthly.loc[
        df_monthly.index >= splice1, 'DTWEXBGS'
    ]

    df_monthly['DOLLAR_INDEX'] = pd.concat([seg_pre95, seg_95_05, seg_post06])
    n_obs = df_monthly['DOLLAR_INDEX'].notna().sum()
    print(f'Dollar index spliced: {n_obs} observations '
          f'(scale1={scale1:.4f}, scale2={scale2:.4f})')

# ── Baa-Aaa spread ────────────────────────────────────────────────────
if 'DBAA' in df_monthly.columns and 'DAAA' in df_monthly.columns:
    df_monthly['BAA_AAA_SPREAD'] = df_monthly['DBAA'] - df_monthly['DAAA']
    print('Baa-Aaa spread computed')

Dollar index spliced: 432 observations (scale1=0.9170, scale2=1.2247)
Baa-Aaa spread computed

In [11]:
macro_var = {
    # Real activity
    'INDPRO':         'industrial_production',
    'W875RX1':        'real_person_income',

    # Labour market
    'UNRATE':         'unemployment_rate',
    'ICSA':           'initial_jobless_claims',
    'CCSA':           'continuing_claims',

    # Inflation
    'CPIAUCSL':       'cpi',

    # Energy / commodities
    'DCOILWTICO':     'oil_price',

    # Financial conditions
    'VIXCLS':         'vix',
    'BAA10Y':         'credit_spread',
    'BAA_AAA_SPREAD': 'baa_aaa_spread',
    'T10Y2Y':         'yield_curve_slope',

    # Monetary policy
    'FEDFUNDS':       'fed_funds_rate',

    # Sentiment & housing
    'UMCSENT':        'consumer_sentiment',
    'HOUST':          'housing_starts',

    # Money supply
    'M2SL':           'm2_money_supply',

    # Dollar index (TWEXB spliced with DTWEXBGS — see cell above)
    'DOLLAR_INDEX':   'dollar_index',
}

# Rename, drop raw series no longer needed, keep only mapped columns
df = df_monthly.rename(columns=macro_var)
drop_cols = [c for c in ['DBAA', 'DAAA', 'TWEXMMTH', 'TWEXB', 'DTWEXBGS']
             if c in df.columns]
df = df.drop(columns=drop_cols)
df = df[[c for c in macro_var.values() if c in df.columns]]
print(f'Final columns ({len(df.columns)}):')
print(list(df.columns))
df.head()

Final columns (16):
['industrial_production', 'real_person_income', 'unemployment_rate', 'initial_jobless_claims', 'continuing_claims', 'cpi', 'oil_price', 'vix', 'credit_spread', 'baa_aaa_spread', 'yield_curve_slope', 'fed_funds_rate', 'consumer_sentiment', 'housing_starts', 'm2_money_supply', 'dollar_index']

,industrial_production,real_person_income,unemployment_rate,initial_jobless_claims,continuing_claims,cpi,oil_price,vix,credit_spread,baa_aaa_spread,yield_curve_slope,fed_funds_rate,consumer_sentiment,housing_starts,m2_money_supply,dollar_index
1990-01-31,61.7290,7184.9,5.4,345000.0,2316000.0,127.5,22.69,25.36,1.68,0.96,0.15,8.23,93.0,1551.0,3166.8,113.174548
1990-02-28,62.2896,7210.5,5.3,350000.0,2347000.0,128.0,21.55,21.99,1.68,0.94,0.08,8.24,89.5,1437.0,3179.2,113.226110
1990-03-31,62.5999,7216.8,5.2,346000.0,2365000.0,128.6,20.34,19.73,1.58,0.84,0.01,8.28,91.3,1289.0,3190.1,115.508660
1990-04-30,62.4359,7262.7,5.4,363000.0,2403000.0,128.9,18.50,19.52,1.50,0.91,0.08,8.26,93.9,1248.0,3201.6,115.502904
1990-05-31,62.6258,7252.9,5.4,359000.0,2431000.0,129.1,17.47,17.37,1.71,0.94,0.10,8.18,90.6,1212.0,3200.6,113.922498

In [25]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 432 entries, 1990-01-31 to 2025-12-31
Freq: ME
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   industrial_production   432 non-null    float64
 1   real_person_income      432 non-null    float64
 2   unemployment_rate       432 non-null    float64
 3   initial_jobless_claims  432 non-null    float64
 4   continuing_claims       432 non-null    float64
 5   cpi                     432 non-null    float64
 6   oil_price               432 non-null    float64
 7   vix                     432 non-null    float64
 8   credit_spread           432 non-null    float64
 9   baa_aaa_spread          432 non-null    float64
 10  yield_curve_slope       432 non-null    float64
 11  fed_funds_rate          432 non-null    float64
 12  consumer_sentiment      432 non-null    float64
 13  housing_starts          432 non-null    float64
 14  m2_money_supply         432 non-null    float64
 15  dollar_index            432 non-null    float64
dtypes: float64(16)
memory usage: 57.4 KB

In [13]:
df.to_csv('../data/macro_data.csv')

# Market Data

In [14]:
tickers = ['VUSTX', 'VFINX']

In [15]:
asset = yf.download(tickers=tickers, start='1990-01-01', end='2025-12-31', interval='1mo')['Close']

[*********************100%***********************]  2 of 2 completed

In [16]:
asset.head()

Ticker          VFINX     VUSTX
Date
1990-01-01  15.304581  1.057725
1990-02-01  15.499675  1.054999
1990-03-01  15.792304  1.050333
1990-04-01  15.506113  1.021528
1990-05-01  17.009085  1.067753

In [17]:
# data downloaded from gold.org
gld = pd.read_excel('../data/Gold_price_averages_in_a range_of_currencies_since_1978.xlsx',
                    sheet_name="Monthly_Avg", 
                    index_col=2,
                    header=5)
gld.index.name = "Date"
# selecting only USD price
gld = gld['USD']
gld.name = 'GLD'
gld.head()

Date
1978-01-31    207.83
1978-02-28    227.27
1978-03-31    245.67
1978-04-28    242.05
1978-05-31    239.16
Name: GLD, dtype: float64

In [18]:
gld.index = gld.index.to_period('M').to_timestamp()
gld.head()

Date
1978-01-01    207.83
1978-02-01    227.27
1978-03-01    245.67
1978-04-01    242.05
1978-05-01    239.16
Freq: MS, Name: GLD, dtype: float64

In [19]:
asset_data = asset.join(gld, how="left").resample('ME').last()

In [20]:
asset_data.head()

                VFINX     VUSTX     GLD
Date
1990-01-31  15.304581  1.057725  376.95
1990-02-28  15.499675  1.054999  383.64
1990-03-31  15.792304  1.050333  363.83
1990-04-30  15.506113  1.021528  363.33
1990-05-31  17.009085  1.067753  358.38

In [21]:
market_var = {
    #Equity
    "VFINX": "index_fund",

    #Bonds
    "VUSTX": "treasury_fund",

    #Gold
    "GLD": "gold_fund"
}

In [22]:
asset_data = asset_data.rename(columns=market_var)

In [23]:
asset_data.isna().sum()

index_fund       0
treasury_fund    0
gold_fund        0
dtype: int64

In [24]:
asset_data.to_csv("../data/market_data.csv")